include: package:lints/recommended.yaml

linter:
  rules:
    - prefer_single_quotes
    - unawaited_futures
    - sort_child_properties_last
    - sort_constructors_first

analyzer:
  exclude:
    - dict/**
