name: mdict_reader
description: mdict reader.
version: 0.0.1
homepage: https://github.com/qingshan/mdict_reader

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  xml: ^5.1.0
  args: ^2.1.0
  pointycastle: ^3.0.1

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
